### ISSUE TITLE
[DataCap Application] USGS

### ISSUE THREAD

**Issue by gimims** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#12]
### Version

1

### DataCap Applicant

DataVault Solutions

### Project ID

DataVault Solutions-004

### Data Owner Name

USGS

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.usgs.gov/

### Social Media Handle

https://www.usgs.gov/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1q4ywjzcyw7osmkcwqmr5asaf5sl2bh6zvn7umci

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DataVault Solutions is a leading company specializing in data storage and management. We provide reliable, secure, and efficient data storage solutions to help our clients manage and protect their critical business data.

As an innovative technology company, DataVault Solutions is dedicated to providing customized data storage solutions for businesses across various industries. Our team consists of experienced data management and technical experts with extensive knowledge and skills to address data requirements of different scales and complexities.

Our core products include high-performance storage systems, cloud storage solutions, backup and recovery services, and data security solutions. Our solutions are designed to deliver reliability, scalability, and flexibility to meet the ever-growing data storage needs of our clients.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
USGS (United States Geological Survey) is a renowned open data website that serves as a valuable resource for a wide range of scientific information. This publicly accessible platform acts as a repository for diverse categories of data, including biology, climate, coastlines, ecosystems, geology, natural disasters, oceans, cartography, and planetary science.

With an extensive collection of data, USGS houses a staggering 10 Petabytes (10 Pib) of metadata. This vast wealth of information is made available to the public, allowing users to freely download, store, and utilize the data for various purposes.

USGS plays a crucial role in advancing scientific research, environmental studies, and resource management. The website serves as a hub for researchers, policymakers, educators, and the general public, offering a wealth of knowledge and insights into our natural world.

The data hosted on USGS covers a broad spectrum of disciplines, providing valuable insights into the Earth's systems and processes. From studying climate patterns and understanding geological formations to analyzing ecosystems and managing natural hazards, the website offers a comprehensive suite of data resources.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://www.usgs.gov/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02036170
f02036171
f03073961
f03073919
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by gimims** [comment]
Hope to get your help and support

**Comment by TOPPOOL-LEE** [comment]
Hi, @gimims.

Thank you for applying.

I would like to ask you some questions for DC allocation.

In the last LDN, several people applied for DC using EMPIAR, and it was also stored in the filecoin network.
You also requested DC allocation, is there a specific reason?

Have you or your organization ever applied for DC as a material for EMPIAR to the previous LDN?

Do you have any experience applying for DC with other data in your previous LDN? If so, please let me know the application link.

Of the SP list you say to save, f03053817 is just the FIL address, all the remaining 11 lists are located in Hong Kong. This doesn't fit the FIL+ distribution rule. DC will not be assigned unless there is SP in other regions, do you understand?

**Comment by gimims** [comment]
Thank you for your reply.

The data on usgs is continuously growing, with a total of 15 P of data. If create 10 backups, can apply for a 150P DCr. Currently, no one has fully stored the data on the Filecoin network.

We haven't applied for a data center from anyone . We can assure you that we are only applying to you.

Although we don't have experience with DC, we have been working with CC for three years. We hope to have DC to reduce the number of machines. We have borrowed FIL from a lending platform, and the data is ready in advance. We hope to receive your assistance.

We will add f03064819, located in South Korea.

Sincerely, we hope to receive your help.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
Looks like it's been used up, waiting for data update

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
![330656262-80dd4ca6-fc46-4f70-8563-34682609b3d2](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/142089399/b1bbc617-ca4e-4b26-85d6-c5f05a228d1f)
![330656238-695b0d2e-b850-447e-8d90-d6b36a22c04f](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/142089399/ce6f80c2-23ab-4830-bd36-fac53aa16887)
![330656229-bda160fa-7825-460e-869a-04e59d00ed72](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/142089399/34150a9c-c38d-4c80-b614-21056173d0bb)
![330656254-f79e1ed8-194d-45d1-b873-3181dc299418](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/142089399/a13de750-7bd4-43b6-aa94-25b6d478fb61)

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by kkk666l** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
检查器：手动触发
