### ISSUE TITLE
[DataCap Application] <Global Health Obsevatory>

### ISSUE THREAD

**Issue by AlfredZKY** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#18]
### Version

1

### DataCap Applicant

DataFortress

### Project ID

DataFortress-Health-WHO-GHO24

### Data Owner Name

World Health Organization

### Data Owner Country/Region

Switzerland

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.who.int/

### Social Media Handle

Twitter: https://x.com/WHO

### Social Media Type

Twitter

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

400Tib

### Number of replicas to store

7

### Weekly allocation of DataCap requested

1024TiB

### On-chain address for first allocation

f14zmgrcgayihubfptjpn42xs2tgk7cpkjxgnjsyq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Data Fortress is a leading organization dedicated to providing exceptional data services for AI firms and data science research. We specialize in data acquisition, storage, and analysis, ensuring our clients access accurate, secure, and comprehensive data solutions. Our mission is to empower AI and research projects with the highest quality data, driving innovation and excellence in the field of data science.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Providing better health information around the world is a core goal of the World Health Organization, which publicly releases their global health data through the Global Health Observatory (GHO). The GHO is a portal for understanding and analyzing the health situation and major issues.
The various datasets are organized by themes such as mortality, health systems, communicable and noncommunicable diseases, medicines and vaccines, health risks, etc. WHO health statistics are the best source of global health information and are also used by the Centers for Disease Control and Prevention in the United States.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
http://www.who.int/gho/maternal_health/reproductive_health/en/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f01422327 - Japan
f02252023 - Japan
f02252024 - Japan
f01989013 - Malaysia
f01989014 - Malaysia
f01989015 - Malaysia
f02105010 - Malaysia
f01111110 - Vietnam (potential participant)
f01909705 - Vietnam (potential participant)
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by TOPPOOL-LEE** [comment]
Thanks for your application:

Please tell me if you have relevant experience and how you will prepare the data.
Why did you choose this data set.
How much data have you downloaded? Do you need our help?
Will you save unseal and support spark?

**Comment by AlfredZKY** [comment]
Please tell me if you have relevant experience and how you will prepare the data.
 We have had some experience in onboarding data to Filecoin network already, about 2PiB of data. And we have our customized tools to prepare and distribute the data to SPs. 

Why did you choose this data set.
 We believe that this dataset is important to human society and it worth keeping multiple copies. 

How much data have you downloaded? Do you need our help?
 We have downloaded more than 300TiB of data, and we estimate that we will just be on time. Thanks!

Will you save unseal and support spark?
 We always ask our collaborators to store hot copies. Not all of them support spark for now, though they are working towards it. For those who does not support spark yet, they will provide commands that can be publicly verified for retrieval.

**Comment by TOPPOOL-LEE** [comment]
Please list the SP, company name and geographical location in detail, thank you!

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
https://filecoinpulse.pages.dev/client/f03150546/  There was a delay in the bot, and we manually checked the distribution and retrieval to support the second round. Looking forward to seeing the next round of bot updates.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by AlfredZKY** [comment]
![2024-07-11 12 05 59](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/32631293/c9030fde-dbf5-42e6-9446-e1eaeab3ac84)
![2024-07-11 12 06 05](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/32631293/7b286534-f731-4f38-aae3-513a581be370)
![2024-07-11 12 06 08](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/32631293/d9c2e637-fbda-45e4-880d-d2b053b1e48e)
![2024-07-11 12 06 12](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/32631293/3cb9f4d0-ee3a-44e0-acfa-c8505419a50e)
![2024-07-11 12 06 57](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/32631293/8d2f07b5-d6e8-45c6-aecb-50efe298abea)
![2024-07-11 12 05 52](https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/32631293/007a1247-4865-45eb-9a85-8e1942b06197)
We searched most of the transactions and they are normal and we hope to get more support from you.  
Thank you!

**Comment by AlfredZKY** [comment]
Dear allocator, we are running very low on the remaining DC. So far, the SPs we collaborated with is the same as the disclosed SPs in our application and all of them support public retrieval. We hope to receive further support from you. Thanks!

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
We have communicated with the client, and all the SPs can be retrieved. We have also manually checked them.

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
It seems that there are still 3 SPs that do not support Spark. I hope to see better data.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger
