### ISSUE TITLE
[DataCap Application] National Radio Astronomy Observatory

### ISSUE THREAD

**Issue by szalongdzyxgs** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#20]
### Version

1

### DataCap Applicant

Quasar

### Project ID

Quasar-2

### Data Owner Name

National Radio Astronomy Observatory

### Data Owner Country/Region

United States

### Data Owner Industry

Professional Services (Legal, Consulting, Advising)

### Website

https://data.nrao.edu/portal/#/

### Social Media Handle

https://data.nrao.edu/portal/#/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1ndqycngvpma4gq7hvk5u7gxekivyyusqgtrxpwi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Quasar's most notable strength lies in its deep expertise in IPFS technology. The company's core technical team has over 3 years of IPFS development experience and a thorough understanding of the principles and applications of distributed storage systems. They have leveraged IPFS to build Quasar's own data management platform, enabling fast, secure, and scalable data storage and sharing.

Bolstered by its exceptional IPFS capabilities, Quasar provides clients with a one-stop solution covering data collection, cleaning, analysis, and visualization. The company's data analysis tools are highly acclaimed for their ability to help clients uncover valuable insights hidden within their data. Quasar also offers blockchain-based data auditing and copyright management services to ensure the security and traceability of clients' data assets.

Looking ahead, Quasar will continue to focus on the research and application of IPFS and other cutting-edge technologies, striving to become a leading provider of data innovation services in Europe. Guided by client needs, the company will constantly optimize its products and services, injecting new momentum into the digital transformation of enterprises.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Founded in 1956, NRAO provides the most advanced radio telescope facilities and information to the international scientific community. Currently, https://data.nrao.edu/portal/#/ has stored 4.3PB of data.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
https://www.internationalgenome.org/data
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Africa, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02956383   Hong Kong
f03148950    Hong Kong
f03035686   Shenzhen, Guangdong, CN
f03068013   Hong Kong
f03136267   Hong Kong
f03144077   Hong Kong
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by TOPPOOL-LEE** [comment]
Thanks for your application:

1. Please tell me if you have relevant experience and how you will prepare the data.
2. Why did you choose this data set.
3. How much data have you downloaded? Do you need our help?
4. Will you save unseal and support spark?

**Comment by TOPPOOL-LEE** [comment]
Are there any updates here?

**Comment by TOPPOOL-LEE** [comment]
Please list the SP, company name and geographical location in detail, thank you!

**Comment by szalongdzyxgs** [comment]
We have mature technical development experience, and can batch download data and generate car files through scripts. When starting the script, you can specify the download data batch parameter to automatically download the source data. While generating the car, the correspondence between the source data and the car file will be saved to a CSV file for record and query.
This dataset has basically not been used by anyone, so we want to store the files on the Filecoin network.
So far, we have completed the generation of 200TB of car files, corresponding to about 140TB of source data.
We require the Storage Provider (SP) to store the backup files according to the requirements, and to keep the unsealed data.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
https://filecoinpulse.pages.dev/client/f03150549/,There was a delay in the bot, and we manually checked the distribution and retrieval to support the second round. Looking forward to seeing the next round of bot updates.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
It looks pretty good.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
Disclosed SP:
f02956383 Hong Kong
f03148950 Hong Kong
f03035686 Shenzhen, Guangdong, CN
f03068013 Hong Kong
f03136267 Hong Kong
f03144077 Hong Kong

Cooperating SP:
f03035686, f03144077, f03136267, f03148950, f03068013

Except that f02956383 does not start, other SP data are consistent

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by szalongdzyxgs** [comment]
Our pledge has been received and we are about to start. Can you continue to support us? Thank you.

**Comment by szalongdzyxgs** [comment]
checker:manualTrigger

**Comment by szalongdzyxgs** [comment]
checker:manualTrigger

**Comment by szalongdzyxgs** [comment]
It may be a bot statistics error. We should not store duplicate data.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
https://github.com/fidlabs/allocator-tooling/issues/73

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger
