### ISSUE TITLE
[DataCap Application] <AWS open data> - <Aind_mouse>

### ISSUE THREAD

**Issue by liruior** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#34]
### Version

1

### DataCap Applicant

Allen Institute

### Project ID

1

### Data Owner Name

Allen Institute

### Data Owner Country/Region

American Samoa

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/allen-nd-open-data/

### Social Media Handle

liruior

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

900TiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

2PiB

### On-chain address for first allocation

f1nnoi4jw7eauijpcjffhcayiybj2y55zlpce3qfi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Allen Institute for Neural Dynamics (AIND) is committed to FAIR, Open, and Reproducible science. We therefore share all of the raw and derived data we collect publicly with rich metadata, including preliminary data collected during methods development, as near to the time of collection as possible.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Mouse Neuroanatomy and Physiology Data
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Packing data using singularity
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://allen-mouse-brain-atlas/ 190.0 TiB
aws s3 ls --no-sign-request s3://aind-open-data/   720.5 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02368946 Huhehaote
f02362412 California
f02639492 California
f02822222 Hong Kong
f03166666 Hongkong
f03166668 Hongkong
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by liruior** [comment]
> Thank you for applying for DC:
> 
> 1. Does your SP support Spark?

All support spark

> 2. How do you process data? Do you need our help?

Packing data using singularity

> 3. Are you ready?

yes

**Comment by liruior** [comment]
checker:manualTrigger

**Comment by liruior** [comment]
256T is more than 75% utilized and it appears that the robot's data is not updated in a timely manner
Here are some of the SP retrieval rates, can you approve the next round?
![企业微信截图_17249017923664](https://github.com/user-attachments/assets/8dde7ec2-e416-4550-9316-335823ffb1b9)

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
In the first round, the bot was not updated. It will temporarily support the second round and expect data updates tomorrow.

**Comment by liruior** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
The filled in sp is the same as the actual sp of cooperation, except that the geographical location of f02368946 is different in the city.
The sp is distributed in two continents and is relatively scattered.
All sps support spark. Hope to improve the retrieval rate of f02822222.
Support this round

**Comment by TOPPOOL-LEE** [comment]
<img width="1117" alt="WX20240902-111825@2x" src="https://github.com/user-attachments/assets/b23ea3ee-9ecc-4a63-bddc-02ae74e1ea77">

**Comment by liruior** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
https://github.com/fidlabs/allocator-tooling/issues/73

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger
