### ISSUE TITLE
[DataCap Application] ePublishing

### ISSUE THREAD

**Issue by nike-mp** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#38]
### Version

1

### DataCap Applicant

ePublishing

### Project ID

ePublishing-01

### Data Owner Name

ePublishing

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.epublishing.com/about/

### Social Media Handle

https://www.epublishing.com/about/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1gtr3oao3yhx6hjtk64oattob6jjimjgunkvxhpy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
ePublishing is an integrated modern media tech stack driving revenue, improving productivity, and increasing engagement for publishers of content and data. They streamline editorial and audience workflows, amplify content delivery, diversify and grow revenue, and leverage a unified, data-first publishing ecosystem.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
ePublishing is an integrated modern media tech stack driving revenue, improving productivity, and increasing engagement for publishers of content and data. They streamline editorial and audience workflows, amplify content delivery, diversify and grow revenue, and leverage a unified, data-first publishing ecosystem.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
The data being stored are the archives and historical editorial and images from media companies - from daily newspapers to monthly magazines - that may reach back as far as 100 years.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03151449
f03151456
f03178077
f03178144
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nike-mp** [comment]
Could you please list the technical solutions in detail?
Could you tell me why you applied for so many DCs? Can the total number of DCs you applied for be reduced?
Could you please list the names of your cooperating sps, geographical locations and companies?
Are you sure you can support Spark?

**Comment by TOPPOOL-LEE** [comment]
Could you please list the technical solutions in detail?
Could you tell me why you applied for so many DCs? Can the total number of DCs you applied for be reduced?
Could you please list the names of your cooperating sps, geographical locations and companies?
Are you sure you can support Spark?
