### ISSUE TITLE
[DataCap Application] Allen Institute for Neural Dynamics

### ISSUE THREAD

**Issue by yse88483** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#4]
### Version

1

### DataCap Applicant

DATADAO

### Project ID

DATADAO-01

### Data Owner Name

Allen Institute for Neural Dynamics

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/allen-nd-open-data/

### Social Media Handle

https://registry.opendata.aws/allen-nd-open-data/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

12

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

1.5

### Unit for expected size of single dataset

PiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

250

### Unit for weekly allocation of DataCap requested

TiB

### On-chain address for first allocation

f14yyeo5rvwufum4zq2cuvyktfkwjbvatk76fcpvq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DATADAO is built upon technical expertise and utilizes proprietary programs and advanced tools to provide customized car data packaging services to clients. Our team boasts extensive experience and proficiency in utilizing cutting-edge tools such as go-graphsplit and singularity to ensure efficient and accurate data packaging. Our service process encompasses the following key points:

Technical Expertise: Our team possesses rich technical expertise in utilizing advanced tools. By leveraging tools like go-graphsplit and singularity, we ensure the efficiency and accuracy of data packaging. These tools aid us in processing and packaging client-provided data to meet the storage requirements of the Filecoin network.

Data Processing Flow: We employ proprietary programs to segment, package, and compress client-provided data, ultimately generating ZIP files ranging from 28-32GB in size to align with the storage requirements of the Filecoin network. Through these services, we effectively assist clients in processing and preparing data for storage and usage on the Filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Allen Institute for Neural Dynamics (AIND) is committed to FAIR, Open, and Reproducible science. We therefore share all of the raw and derived data we collect publicly with rich metadata, including preliminary data collected during methods development, as near to the time of collection as possible.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Yes，I am data preparer, DATADAO have technical team that specializes in providing Car data packaging services to our clients, which include: 1. technical expertise: our team is skilled in using advanced tools such as go-graphsplit, singularity, etc. to ensure efficient and accurate data packaging. 2. Data Processing Flow: We use self-developed programs to cut, package, and compress the data provided by our clients into 28-32GB zip files to meet the storage requirements of the Filecoin network. Through these services, we are able to effectively help our clients process and prepare data for storage and use on the Filecoin network.
```

### Please share a sample of the data

```text
https://registry.opendata.aws/allen-nd-open-data/

aws s3 ls --no-sign-request s3://aind-open-data/


aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://aind-open-data/ | grep "Total Size:"
Total Size: 2.3 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02941878 、f02941888 、f02941882 、f02941891 、f02941885 、f02941886、f02945259 、f02945258
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by yse88483** [comment]
is there have any news？

**Comment by TOPPOOL-LEE** [comment]
It looks like you applied for too many, we can only start with one
