### ISSUE TITLE
[DataCap Application] Pangeo Community

### ISSUE THREAD

**Issue by udi1231239** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#40]
### Version

1

### DataCap Applicant

Pangeo Community

### Project ID

001

### Data Owner Name

Pangeo Community

### Data Owner Country/Region

United States

### Data Owner Industry

IT & Technology Services

### Website

https://pangeo-data.github.io/pangeo-cmip6-cloud/

### Social Media Handle

[at]pangeo_data (Twitter)

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

8PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1 PiB

### On-chain address for first allocation

f17cuovxm2hqymgvwy5vxhyescpsy62lkqrnmuhha

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text

Our team is a very pure development team, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. 

```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Zarr formatted data and Netcdf formatted data.
The sixth phase of global coupled ocean-atmosphere general circulation model ensemble.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
After we download data from the Internet, the data is cut into disks through Singularity, and then the hard disk is mailed to the SPs.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
There are some people who have stored this data in 2021 or earlier, some of the data may expire, I want to store them again.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://cmip6-pds/
aws s3 ls --no-sign-request s3://esgf-world/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How did you find your storage providers

Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03231154, HongKong
f03228906, China
f03157910, Shenzhen, China
f03157905, Shenzhen, China
f03218576 US
f03215853 US
f01025366, Qingdao, China
f0122215,Qingdao, China
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by olh-a11y** [comment]
Use Python automation program to download and issue orders through boost
We have cooperated with 10 SPs, and the average demand of each SP is 2PiB each, so we do not want to reduce the total number of DCs. Is there an upper limit on the total amount of data applied for?
f03231154, HongKong
f03218576, Portland, United States
f03215853, Portland, United States
f03157910, Shenzhen, China
f03157905, Shenzhen, China
f03220172, Singapore
f03220176, HongKong
f01025366, Qingdao, China
All can support Spark. I hope to get your help. Thank you.

**Comment by udi1231239** [comment]
Use Python automation program to download and issue orders through boost
We have cooperated with 10 SPs, and the average demand of each SP is 2PiB each, so we do not want to reduce the total number of DCs. Is there an upper limit on the total amount of data applied for?
f03231154, HongKong
f03218576, Portland, United States
f03215853, Portland, United States
f03157910, Shenzhen, China
f03157905, Shenzhen, China
f03220172, Singapore
f03220176, HongKong
f01025366, Qingdao, China
All can support Spark. I hope to get your help. Thank you.

**Comment by TOPPOOL-LEE** [comment]
I think your total number of applications is still too large! Hope it can be reduced to less than 10P.

**Comment by udi1231239** [comment]
OK, we have complied with your request and modified the application form. We hope to get your help.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
Although a bug of duplicate datasets occurred, the cooperating SP is the same as the disclosed SP. SP supports Spark.We decided to support it and hope the bug will be fixed as soon as possible.

**Comment by udi1231239** [comment]
checker:manualTrigger

**Comment by udi1231239** [comment]
checker:manualTrigger

**Comment by udi1231239** [comment]
Dear @TOPPOOL-LEE  and technician, our team checked the program we developed and it is normal, so there is no possibility of duplicate data, especially since all three sps have this problem, there must be a bug.
We think it may be that the data has not been updated, or there is a bug in the bot. We have followed up on the problem we encountered in 73.
However, according to the official technicians, it seems that it will take time to solve this bug, so we hope to be supported again so that we have enough time to continue to serve customers while waiting for the update.
Thank you.

**Comment by udi1231239** [comment]
<img width="1110" alt="WX20241106-113356@2x" src="https://github.com/user-attachments/assets/e9acd128-b9ca-4ab5-9486-5ed23d641d06">

**Comment by TOPPOOL-LEE** [comment]
Let's wait 30 hours and hopefully the bot will update. Please keep patient @udi1231239

**Comment by TOPPOOL-LEE** [comment]
In addition, there are some changes between your disclosed SP and the cooperating SP,  please explain.

**Comment by udi1231239** [comment]
> Use Python automation program to download , orders through boost We have cooperated with 10 SPs, and the average demand of each SP is 2PiB each, so we do not want to reduce the total number of DCs. Is there an upper limit on the total amount of data applied for? f03231154, HongKong f03228906, China f03157910, Shenzhen, China f03157905, Shenzhen, China f03218576 US f03215853 US f01025366, Qingdao, China f0122215,Qingdao, China All can support Spark. I hope to get your help. Thank you.

Dear Allocator,Before you sign the first round for us, we previously disclosed the updates of SP on GitHub, but they were not synchronized to the submission form here.
To reduce misunderstandings, we have already updated the application form. Thank you.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by udi1231239** [comment]
We have started #53, we have closed 40, hoping to get help to verify whether there is a problem with our technical solution or with the bot, thank you.

**Comment by TOPPOOL-LEE** [comment]
https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/42

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger
