### ISSUE TITLE
[DataCap Application] Sloan Digital Sky Survey

### ISSUE THREAD

**Issue by usejsi** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#46]
### Version

1

### DataCap Applicant

Sloan Digital Sky Survey

### Project ID

001

### Data Owner Name

Sloan Digital Sky Survey

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.sdss.org/

### Social Media Handle

https://www.sdss.org/

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

600TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1zfi4maamodbdpizcewkwjctp43v7tzy5ucc5lny

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I joined the filecoin network in 2021, and made the cc package of fil at the very beginning.  In 2022, we did a part of cc to dc conversion, and now we have a planned continuous development of data storage.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Sloan Digital Sky Survey (SDSS) is one of the most ambitious and influential surveys in the history of astronomy. 
The SDSS project has established in 2000, five periods, 18 times data released. The 19th DR will be in 2024. 
As for now, there are about 750TB volume of data can be accessed.  5.5 million directories, 400 million files. 
DR1-DR7: SDSS-I, 2000-2005; SDSS-II, 2005-2008), it obtained deep, multi-color images covering more than a quarter of the sky and created 3-dimensional maps containing more than 930,000 galaxies and more than 120,000 quasars.
DR8: contains all images from the SDSS telescope - the largest color image of the sky ever made. It also includes measurements for nearly 500 million stars and galaxies, and spectra of nearly two million. 
DR9 contains the first release of BOSS spectroscopy to the public as well as several significant updates to the cumulative SDSS archive
DR10 contains the first release of APOGEE infrared Galactic spectroscopy as well as cumulative updates to the BOSS optical extragalactic spectroscopy archive
The SDSS began regular survey operations in 2000, after a decade of design and construction.  It has progressed through several phases, SDSS-I (2000-2005), SDSS-II (2005-2008), SDSS-III (2008-2014), and SDSS-IV (2014-2020).  Each of these phases has involved multiple surveys with interlocking science goals.  The three surveys that comprise SDSS-IV are eBOSS (including SPIDERS and TDSS), APOGEE-2, and MaNGA (including MaStar),
The SDSS-V Pioneering Panoptic Spectroscopy program started observing in October 2020, and consists of three surveys, known in SDSS-V terminology as mapper programs.

Milky Way Mapper is a multi-object spectroscopic survey to obtain near-infrared and/or optical spectra of more than 4 million stars throughout the Milky Way and Local Group
Local Volume Mapper is an optical, integral-field spectroscopic survey that will target the Milky Way, Small and Large Magellanic Clouds, and other Local Volume galaxies
Black Hole Mapper is a multi-object spectroscopic survey that emphasizes optical spectra (often also with multiple epochs of spectroscopy) for more than 300,000 quasars
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
http://classic.sdss.org/dr7/
http://sdss3.org/
https://www.sdss4.org/dr17/data_access/volume/
https://dr17.sdss.org/sas/dr17/apogee/spectro/aspcap/
https://dr17.sdss.org/sas/dr17/apogee/spectro/speclib/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03151449, Shenzhen, China           
f03151456, Shenzhen, China               
f03179570, Singapore       
f03179555, Singapore           
f03178077, Tokyo, Japan   
f03178144, Tokyo, Japan   
f03179572, US 
f03214937, US 
f03229932, South Korea
f03229933, South Korea
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by TOPPOOL-LEE** [comment]
<img width="1116" alt="WechatIMG32139" src="https://github.com/user-attachments/assets/6bdb33c0-8485-487e-9912-96b2407a6498">

**Comment by TOPPOOL-LEE** [comment]
The data of this website is about 650TiB. You requested a total of 8PiB, 8 backups, and a single data set size of 1024TiB. It seems too much.Can you reduce the total amount you requested?

**Comment by usejsi** [comment]
We have adjusted it according to your request, thank you

**Comment by TOPPOOL-LEE** [comment]
Could you list the technical solutions in detail?
Could you please list the names of your cooperating sps, geographical locations and companies?
Are you sure you can support Spark?

**Comment by usejsi** [comment]
I hope we are close to getting approval.
We have developed our own technical solutions, including some crawlers, cutting tools, etc.
The SPs we cooperate with are mainly fund companies, large customers and independent investors. Some friends who previously mined BTC contacted us and hoped to join Filecoin.
Spark can be supported, thank you.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
Please explain the duplicate data, thanks.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
This is the retrieval rate when I sign for you
<img width="1035" alt="WX20241204-114657@2x" src="https://github.com/user-attachments/assets/3f938396-c3a6-485e-9ce1-ba2e12194b48">
This is your retrieval rate. now
<img width="1030" alt="WX20241204-114715@2x" src="https://github.com/user-attachments/assets/a43d146e-63f2-4e65-a4ae-43e40f78c2fa">
What happened?

**Comment by usejsi** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
Sorry, the data center was relocated last week, so the retrieval rate has decreased. It has started to recover and will be fully restored in about 3 days.
We will keep our promise and ensure that every sp supports spark.

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
> ## DataCap and CID Checker Report Summary[1](#user-content-fn-1-647f0ee6686d2df1c980ee8ef3ba0a3a)
> ### Storage Provider Distribution
> ✔️ Storage provider distribution looks healthy.
> 
> ⚠️ 100.00% of Storage Providers have retrieval success rate less than 75%.
> 
> ### Deal Data Replication
> ✔️ Data replication looks healthy.
> 
> ### Deal Data Shared with other Clients[2](#user-content-fn-3-647f0ee6686d2df1c980ee8ef3ba0a3a)
> ✔️ No CID sharing has been observed.
> 
> ### Full report
> Click [here](https://check.allocator.tech/report/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/46/1733639943008.md) to view the CID Checker report.
> 
> ## Footnotes
> 1. To manually trigger this report, add a comment with text `checker:manualTrigger` [↩](#user-content-fnref-1-647f0ee6686d2df1c980ee8ef3ba0a3a)
> 2. To manually trigger this report with deals from other related addresses, add a comment with text `checker:manualTrigger <other_address_1> <other_address_2> ...` [↩](#user-content-fnref-3-647f0ee6686d2df1c980ee8ef3ba0a3a)

Although the retrieval rate is fixed, there are some traces of VPN here.

**Comment by TOPPOOL-LEE** [comment]
Why do you use a VPN? Can you explain?

**Comment by usejsi** [comment]
Yes, dear allocators, governance teams, and auditors.
SP does use VPN. We were attacked by hackers and lost a total of 8593 FIL. We use VPN not to modify the geographic location, but to increase security and reduce the possibility of hacker attacks.
Is VPN prohibited?
We believe that security is the most important thing compared to DC. Although we are eager to continue to get your support, it is very dangerous to directly expose the native IP address.

**Comment by usejsi** [comment]
We would like to confirm whether the use of VPN is prohibited, thank you

**Comment by TOPPOOL-LEE** [comment]
Using VPN is not prohibited, there are many Aallocators that allow SP to use VPN. we hope that SP can keep the original geographical location. So it is difficult to bring you the next round. You can look for distributors that support VPN.
