### ISSUE TITLE
[DataCap Application] ESRF

### ISSUE THREAD

**Issue by yse88483** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#5]
### Version

1

### DataCap Applicant

DATADAO

### Project ID

DATADAO-01

### Data Owner Name

ESRF

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.esrf.fr/about

### Social Media Handle

https://www.esrf.fr/about

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

12

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

2

### Unit for expected size of single dataset

PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

250

### Unit for weekly allocation of DataCap requested

TiB

### On-chain address for first allocation

f1luylzsvfmad4ii24q7nviwtyraur4ftyhknsbwi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DATADAO is built upon technical expertise and utilizes proprietary programs and advanced tools to provide customized car data packaging services to clients. Our team boasts extensive experience and proficiency in utilizing cutting-edge tools such as go-graphsplit and singularity to ensure efficient and accurate data packaging. Our service process encompasses the following key points:

Technical Expertise: Our team possesses rich technical expertise in utilizing advanced tools. By leveraging tools like go-graphsplit and singularity, we ensure the efficiency and accuracy of data packaging. These tools aid us in processing and packaging client-provided data to meet the storage requirements of the Filecoin network.

Data Processing Flow: We employ proprietary programs to segment, package, and compress client-provided data, ultimately generating ZIP files ranging from 28-32GB in size to align with the storage requirements of the Filecoin network. Through these services, we effectively assist clients in processing and preparing data for storage and usage on the Filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
With a brand-new generation of high-energy synchrotron, the ESRF is the world's brightest X-ray source and a centre of excellence for fundamental and innovation-driven research in condensed and living matter science. 

On August 2020, the ESRF opened its completely rebuilt x-ray source, ESRF-EBS (Extremely Brilliant Source), the world’s first fourth-generation high-energy synchrotron.

The ESRF - The European Synchrotron Radiation Facility - is the most intense source of synchrotron-generated light, producing X-rays 100 billion times brighter than the X-rays used in hospitals. These X-rays, endowed with exceptional properties, are produced at the ESRF by the high energy electrons that race around the storage ring, a circular tunnel measuring 844 metres in circumference.

The ESRF was conceived as a true European collaboration for the advancement of X-ray science. In 1988, eleven European countries joined forces to build the world’s most performing and bright « third-generation » light source. This visionary project has made an outstanding contribution to the excellence of European science. Almost thirty years later, a new dream saw the light, with the launch of a brand-new generation of high-energy synchrotron, the ESRF's Extremely Brilliant Source. With the support of ESRF's 21 partner countries, EBS provides scientists from all over the world with new opportunities to pioneer innovative science and to addressing the complex global challenges that our society faces.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Yes，I am data preparer, DATADAO have technical team that specializes in providing Car data packaging services to our clients, which include: 1. technical expertise: our team is skilled in using advanced tools such as go-graphsplit, singularity, etc. to ensure efficient and accurate data packaging. 2. Data Processing Flow: We use self-developed programs to cut, package, and compress the data provided by our clients into 28-32GB zip files to meet the storage requirements of the Filecoin network. Through these services, we are able to effectively help our clients process and prepare data for storage and use on the Filecoin network.
```

### Please share a sample of the data

```text
https://www.esrf.fr/about
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02941878 、f02941888 、f02941882 、f02941891 、f02941885 、f02941886、f02945259 、f02945258
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by TOPPOOL-LEE** [comment]
Do you have any experience applying for DC? How many people do you have on your technical team and how do you solve data download and storage i?

**Comment by yse88483** [comment]
Sorry for the late reply. We have enough experience, we have 5 employees dedicated to FIL+ matters, mainly including data processing, downloading, mailing and maintenance. In v3.1 we applied for https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2327. Because v3.1 was not recharged, we did not use it. Now we are all ready. We hope you will approve us.
