### ISSUE TITLE
[DataCap Application] Commoncrawl

### ISSUE THREAD

**Issue by yse88483** [TOPPOOL-LEE/Allocator-Pathway-TOP-POOL#7]
### Version

1

### DataCap Applicant

DATADAO

### Project ID

DATADAO-02

### Data Owner Name

Commoncrawl 

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://commoncrawl.org/

### Social Media Handle

https://commoncrawl.org/

### Social Media Type

Slack

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

2PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1gwje2izkfea2yglv6ujjzrugre5tperpp55qpia

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DATADAO is built upon technical expertise and utilizes proprietary programs and advanced tools to provide customized car data packaging services to clients. Our team boasts extensive experience and proficiency in utilizing cutting-edge tools such as go-graphsplit and singularity to ensure efficient and accurate data packaging. Our service process encompasses the following key points:

Technical Expertise: Our team possesses rich technical expertise in utilizing advanced tools. By leveraging tools like go-graphsplit and singularity, we ensure the efficiency and accuracy of data packaging. These tools aid us in processing and packaging client-provided data to meet the storage requirements of the Filecoin network.

Data Processing Flow: We employ proprietary programs to segment, package, and compress client-provided data, ultimately generating ZIP files ranging from 28-32GB in size to align with the storage requirements of the Filecoin network. Through these services, we effectively assist clients in processing and preparing data for storage and usage on the Filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Common Crawl maintains a free, open repository of web crawl data that can be used by anyone.
Primary training corpus in every LLM.82% of raw tokens used to train GPT-3.Free and open corpus since 2007.Cited in over 8000 research papers.3–5 billion new pages added each month.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
357-resule 
2020-08-25 17:22:47  398.4 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf13.grib2
2020-08-25 17:22:52  396.0 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf14.grib2
2020-08-25 17:22:52  394.6 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf15.grib2
2020-08-25 17:22:52  390.2 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf16.grib2
2020-08-25 17:23:08  387.1 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf17.grib2
2020-08-25 17:23:05  384.8 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf18.grib2
2021-09-28 03:48:22   31.6 KiB index.html

Total Objects: 43282174
   Total Size: 2.1 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Filmine, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02941888 
f02941882 
f02941891 
f02941885
f02941886  
f02945259
f02950965
f02830451
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
You apply too many, you can close the others and then we'll just start with one.

**Comment by nicelove666** [comment]
If you are not preparing the data, who will prepare the data?
Have you applied for DC? If so, please take the link.
Are you ready? Do you need our help?

**Comment by yse88483** [comment]
Sorry, we shouldn't have applied so many , but we have applied for too long and hope you can approve it for us. You can approve any one and I'll close the others. We have enough experience, we have 5 employees dedicated to FIL+ matters, mainly including data processing, downloading, mailing and maintenance. In v3.1 we applied for # 2327. but v3.1 was not recharged, we did not use it. Now we are all ready. We hope you will approve us.

**Comment by nicelove666** [comment]
I decided to sign this for you and then close your other applications. Please do not apply multiple times in the future.

**Comment by yse88483** [comment]
checker:manualTrigger

**Comment by yse88483** [comment]
checker:manualTrigger

**Comment by yse88483** [comment]
The data is not updated.

**Comment by yse88483** [comment]
In the next round, the data will definitely be updated

**Comment by yse88483** [comment]
checker:manualTrigger

**Comment by yse88483** [comment]
The data has not been updated. We have added SPs from other regions.

**Comment by yse88483** [comment]
we will add f03064819（South Korea）

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
As you said, you added "f03064819",
<img width="1007" alt="WX20240511-094024@2x" src="https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/142089399/a21aaeeb-a769-4061-827a-0b61142ffd3c">

**Comment by TOPPOOL-LEE** [comment]
<img width="758" alt="WechatIMG6677" src="https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/assets/142089399/5817101d-6fd9-4fd0-954b-7963b5b21832">

**Comment by yse88483** [comment]
So, can you help me?

**Comment by joshua-ne** [comment]
checker:manualTrigger

**Comment by yse88483** [comment]
Dear allocator, everything looks very good and supports retrieval. The checkbot data is also fully compliant. Can you help us again?

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger

**Comment by galen-mcandrew** [comment]
checker:manualTrigger

**Comment by yse88483** [comment]
Dear @galen-mcandrew galen, @TOPPOOL-LEE , thanks for your support. We have communicated with sp. They are actively studying the Spark code and they will strive to achieve retrieval through spark in the shortest possible time. If the SP is still unable to retrieve through Spark, we will not continue to cooperate with them.

**Comment by yse88483** [comment]
You can flag those SPs if they are unable to improve the retrieval, we will not cooperate with them.

**Comment by yse88483** [comment]
Dear allocator, we have contacted SP again. SP uses the Venus system. SP supports retrieval, but Venus does not support Spark, the data on Spark is not very good. SP is actively assisting Spark to solve the problem.

we promise:
If the SP cannot solve these problems, we will no longer cooperate with these SPs.

**Comment by yse88483** [comment]
checker:manualTrigger

**Comment by TOPPOOL-LEE** [comment]
checker:manualTrigger
